### ISSUE TITLE
Is there way to turn off "The remote name could not be resolved" error being thrown log if server is not available. 

### ISSUE THREAD

**Issue by Spsk78** [urielha/log4stash#19]
Is there way to turn off "The remote name could not be resolved" error being thrown if server is not available. 

Our system logs messages using rollingfileappender and also ealsticsearchappender, the below error message is thrown if the elastic server is not available  

log4net:ERROR Invalid request to ElasticSearch
System.Net.WebException: The remote name could not be resolved: 'server.does.not
.exists'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at log4stash.WebElasticClient.SafeSendRequest(RequestDetails request, Func`1
getRequestStream) in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticClien
t\ElasticClient.cs:line 171

**Comment by urielha** [comment]
Is that preventing from the rollingFileAppender to logging into files? or is this error just annoying and trash your event log?

**Comment by urielha** [comment]
Try add this to your app.config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <appSettings>
        <add key="log4net.Internal.Quiet" value="true"/>
    </appSettings>
</configuration>
```

Read about the internal log (LogLog) of log4net [here (log4net internal debugging)][1].
Try do as they said but instead of `log4net.Internal.Debug` try to put `log4net.Internal.Quiet` to be true.

( Source code of LogLog can be found [here (LogLog.cs)][2] and search for *QuietMode* )

[1]: https://logging.apache.org/log4net/release/faq.html#internalDebug
[2]: https://svn.apache.org/repos/asf/logging/log4net/trunk/src/Util/LogLog.cs
