### ISSUE TITLE
Routing to a specific shard

### ISSUE THREAD

**Issue by bahim** [urielha/log4stash#28]
Hi,

I'm using log4stash to write logs to elasticsearch, i have daily indices (each one with multiple shards).
I want to use routing to write to a specific shard but i didn't find a way to do it with log4stash.
Is it possible to do it with log4stash ?

**Comment by urielha** [comment]
You mean that you want option like [`routing`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-routing) ?
Unfortunately log4stash doesn't have such option yet.
I can add this option in the future.

I have two suggestions for now:
 * Log4stash do have a new option to specify the **document id** source, see details below.
 * Maybe playing with the template would solve your problem? (any combination of document id and template)

**Template:**
For using the template you need to add the `<Template>` tag to your configuration. (full config example can be found [here](https://github.com/urielha/log4stash#almost-full-configuration)). You can find an example of template here: [template.json](https://github.com/urielha/log4stash/blob/master/src/log4stash.Tests/template.json).

**DocumentIdSource:**
You can specify an alternate value for the document id to your event. Search for the `DocumentIdSource` at the example.
Inside the tag you can specify the name of a property of the object you are logging so that the document id will be extracted from it.

**Comment by bahim** [comment]
Hi,

It would be nice of you to add routing option to log4satsh.
In the meantime is use aliases as workaround.

**Comment by eran-gil** [comment]
Hey, look at my new pull request #31 .
It adds a simple routing option to the appender.
@urielha It's pretty similar to the DocumentIdSource logic, so I had the opportunity to improve my code there.
When you have time please look at it :)

**Comment by urielha** [comment]
Took me too much time but at last version 2.0.5 released with this feature.
Have fun :)
