### ISSUE TITLE
@timestamp instead of properties.@timestamp

### ISSUE THREAD

**Issue by johnqa** [urielha/log4stash#33]
Hi, I have a testing project that reports to elasticsearch using log4net with log4stash while the developers use something else for reporting to elasticsearch (not log4net).
My idea would be to create an index common for both projects, but I see that I cannot find a common timestamp.

The developers logs have a @timestamp field why I have a properties.@timestamp and a timestamp.

Could a new field @timestamp be added to logged entries?

Thank you!

**Comment by urielha** [comment]
I don't think I get you, log4stash already **has** a **@timestamp** property.
You can see it [being set here](https://github.com/urielha/log4stash/blob/master/src/log4stash/LogEventFactory/BasicLogEventFactory.cs#L46).

If you want to "move" it or use another value you can use log4stash's filters:
`Add` - can help you with adding new property using already exists ones.
`Remove` - to delete property.
`Rename` - to rename property.

example:
```xml
<ElasticFilters>
       <!-- Removing the default timestamp -->
       <Remove>
          <Key>@timestamp</Key>
       </Remove>
      <!-- adding custom timestamp form 'custom_timestamp_prop_name' -->
      <Add>
        <Key>@timestamp</Key>
        <Value>%{custom_timestamp_prop_name}</Value>
      </Add>
</ElasticFilters>
```

**Comment by johnqa** [comment]
Thank you for pointing me to that... I was using an older index. It works indeed.

May I ask you why the IndexName and IndexType properties only have set, while the other also have get? I am having a scenario where I would like to extract from the log4net config file, the information related to the log4stash appender.

Thank you!

**Comment by urielha** [comment]
The main reason was because indexName and indexType can have different values depending on your logObject (they are using an internal "SmartFormatter").

But you are right, there is no problem to add a getter to query the original configured value of them. I missed that.

Until then, try use reflection to get the private fields of log4stash appender.. I think this should be enough.

I'm Closing this issue.
I will open a follow up issue for the getters (if you have more questions you can ask there)
