### ISSUE TITLE
RestSharp Dependency 

### ISSUE THREAD

**Issue by havascolino** [urielha/log4stash#53]
Dear urielha,
In version 2.2.0 you added a dependency on RestSharp which is an unsigned dll. This will force strongly signed project to sign the the RestSharp dll and then recompile the log4stash project with a reference to the signed dll, which is quite a bother. Please revert to the single dependency only on the log4net dll.

Your,

Ariel

**Comment by urielha** [comment]
Hi,
I will publish soon a new package to let you try if this ok (I am thinking of using ILRepack to pack RestSharp into log4stash.dll)

Stay tuned.
Uriel

**Comment by oltronix** [comment]
Any update on this.? We are stuck on an old version of restsharp and i'm unsure how to resolve it.

**Comment by urielha** [comment]
It's been a year but we are packing Restsharp on newer versions since than but it was a `pre-release` until those days. Really sorry I forgot to update this thread.

The pre-release available here: [2.2.2-pre](https://www.nuget.org/packages/log4stash/2.2.2-pre)
Newer version also available: [2.3.0](https://www.nuget.org/packages/log4stash/2.3.0)
